[package]
name = "c2-engine"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "c2-engine"
path = "src/main.rs"

[dependencies]
serde        = { version = "1", features = ["derive"] }
serde_json   = "1"
anyhow       = "1"
chrono       = { version = "0.4", features = ["serde"] }
clap         = { version = "4", features = ["derive"] }
tracing      = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio        = { version = "1", features = ["full"] }
axum         = { version = "0.7", features = ["ws"] }
tower-http   = { version = "0.5", features = ["trace"] }
notify       = "6"
rusqlite     = { version = "0.31", features = ["bundled"] }
r2d2         = "0.8"
r2d2_sqlite  = "0.24"
sha1         = "0.10"
hex          = "0.4"
rand         = "0.8"
base64       = "0.22"
dirs         = "5"
tokio-util   = "0.7"
walkdir      = "2"
